### ISSUE TITLE
🎁 [Feature Request]: Implement Async Backing in Deliverable 2 EVM Runtime Template

### ISSUE THREAD

**Issue by NM2146** [OpenZeppelin/polkadot-runtime-templates#171]
### What is the feature you would like to see?

Add asynchronous backing capabilities to the EVM runtime template to enhance scalability and support high throughput. This requires integrating async operations and adjusting related components to ensure smooth performance.

**Tasks:**

- Modify the runtime to include async backing support.
- Update dependencies or libraries to ensure compatibility with async operations.
- Test async functionality to ensure stability and performance.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines

**Comment by ggonzalez94** [comment]
@ozgunozerk I think async backing is incorporated in the generic runtime template(from which the EVM builds on). If so can we close this issue?
