### ISSUE TITLE
🏗️ [Core Feature]: Implement CheckMetadataHash extension

### ISSUE THREAD

**Issue by NM2146** [OpenZeppelin/polkadot-runtime-templates#209]
### templates

- [X] Generic Runtime Template
- [X] Evm Template

### What is the key feature we're aiming to implement?

The metadata hash extension in the Polkadot runtime is a feature that ensures the runtime metadata's integrity. By implementing this, you can verify that the metadata remains unchanged, providing an additional layer of security and trust. It helps in detecting unauthorized modifications and ensures that the metadata used by clients and other tools matches the runtime’s actual metadata. This is particularly useful for maintaining consistency and reliability across different deployments and updates.

- [Follow this guide ](https://paritytech.github.io/polkadot-sdk/master/polkadot_sdk_docs/guides/enable_metadata_hash/index.html) on how to integrate the signed extension etc into your runtime

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines

**Comment by SBalaguer** [comment]
To add to Nico's comment:

## Why is this important?
It will allow every runtime developed by OZ and then used by the community to be compatible with the Polkadot Ledger App out of the box.

## What things are needed to achieve this?
1. Be compatible with at least Polkadot-SDK version 1.1.0.
2. Be compatible with Metadata V15.
3. Add the changes to the runtime as detailed on the guide shared by Nico.

I believe 1 and 2 are already done, and 3 should be quite trivial.

**Comment by bkchr** [comment]
> `polkadot-v1.10.0` so this feature will

It is available in the `release-polkadot-v1.10.0` branch.
