### ISSUE TITLE
🏗️ [Core Feature]: impl FeeManager for `evm-template` to match `generic-template`

### ISSUE THREAD

**Issue by 4meta5** [OpenZeppelin/polkadot-runtime-templates#223]
### templates

- [ ] Generic Runtime Template
- [X] Evm Template

### What is the key feature we're aiming to implement?

`generic-template` sets `FeeManager` to
```rust, ignore
 type FeeManager = XcmFeeManagerFromComponents<
        IsChildSystemParachain<primitives::Id>,
        XcmFeeToAccount<Self::AssetTransactor, AccountId, TreasuryAccount>,
    >;
```
while `evm-template` sets it to `()`

Suggested solution is to set the `evm-template` `FeeManager` to the same or a comparable value instead of `()`

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines

**Comment by ggonzalez94** [comment]
@ozgunozerk I'm marking this as closed since the PR was merged to the v2 branch
