### ISSUE TITLE
🐞 [Bug]: Misconfiguration of BlockGasLimit could lead to runtime panic for GasLimitPovSizeRatio

### ISSUE THREAD

**Issue by KitHat** [OpenZeppelin/polkadot-runtime-templates#245]
### templates

- [ ] Generic Runtime Template
- [X] Evm Template

### What happened?

In the EVM runtime template, the [GasLimitPovSizeRatio parameter](https://github.com/OpenZeppelin/polkadot-runtime-templates/blob/master/evm-template/runtime/src/configs/mod.rs#L596) is configured by casting BlockGasLimit:U256 into u64 through as_u64. If the BlockGasLimit is wrongly configured to U256::MAX, this may result in [panic](https://github.com/paritytech/parity-common/blob/d5e9c1d5b52e7a43f843855a0f4fbc319929a681/uint/src/uint.rs#L644-L650) at runtime.

### Expected behavior

* Configure the GasLimitPovSizeRatio to be bounded within u64::MAX. An example configuration can be found in the Polkadot Frontier chain [template](https://github.com/paritytech/frontier-parachain-template/blob/ac10a6a534ea3a6e8f3a433f6ec1e08a7c8b76db/runtime/src/lib.rs#L739)
* Ensure that BlockGasLimit is neither set to zero nor to the maximum value in the runtime, and highlight the criticality of deviating from the standard configuration through inline documentation.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines

**Comment by NithinJ-17** [comment]
Hello @KitHat , I am interested in taking up this issue and will work on configuring the GasLimitPovSizeRatio accordingly. Can I?

**Comment by ggonzalez94** [comment]
@NithinJ-17 this was already fixed on #246, but the issue wasn't marked as closed because it targeted a different branch from main. 
I'm closing this now, but please go through our issues and if you see something that you want to tackle we would be happy to work with you on getting it done 🙂
