### ISSUE TITLE
Update and revize docs

### ISSUE THREAD

**Issue by ozgunozerk** [OpenZeppelin/polkadot-runtime-templates#254]
- [x] fix typos and broken links
- [x] add a new guide for how to test things in zombienet
- [x] add missing sections related to EVM template
- [x] add newly added pallets into generic template configuration description
- [x] move quick start for generic template into its own document
- [x] update `index.adoc` and mention the EVM template there

**Comment by ggonzalez94** [comment]
@ozgunozerk closing this since the PR was merged
