### ISSUE TITLE
🎁 [Feature Request]: Accept DOT as a Gas Fee Payment

### ISSUE THREAD

**Issue by NM2146** [OpenZeppelin/polkadot-runtime-templates#306]
### templates

- [X] Generic Runtime Template
- [X] Evm Template

### What is the feature you would like to see?

As Polkadot’s native token, DOT is widely used across parachains & other projetcs within the ecosystem. To improve the user experience, especially in cross-chain applications, it is important to allow DOT to be used as a gas fee payment token, without requiring the user to manually convert it into the network's native token.

**Proposed Enhancement:**
Implement functionality at the runtime level so that parachains can natively accept DOT for transaction fees. This can be done transparently, converting the fees behind the scenes to the native token required by the network, without users needing to handle the conversion themselves.

By integrating this directly into the runtimes, the feature can be used “out of the box,” providing flexibility to developers and ease of use for end-users. The gas fee mechanism should allow DOT to be automatically routed and converted to the necessary token to pay for network operations.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines

**Comment by kianenigma** [comment]
Is the process to integrate this covered in https://docs.openzeppelin.com/substrate-runtimes/3.0.0-rc/?
