### ISSUE TITLE
🎁 [Feature Request]: Configure pallet_asset_manager for generic-template

### ISSUE THREAD

**Issue by 4meta5** [OpenZeppelin/polkadot-runtime-templates#340]
### templates

- [X] Generic Runtime Template
- [ ] Evm Template

### What is the feature you would like to see?

Requested by during review of pallet wrappers : https://github.com/OpenZeppelin/polkadot-runtime-wrappers/pull/1#issuecomment-2425849352

Also required for the Snowbridge integration as per that comment

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines

**Comment by ozgunozerk** [comment]
Isn't this one the same: https://github.com/OpenZeppelin/polkadot-runtime-templates/issues/222

If so we can close one of those, if not nevermind...
