### ISSUE TITLE
🐞 [Bug]: Zombienet config doesn't work with `paseo-local`

### ISSUE THREAD

**Issue by ozgunozerk** [OpenZeppelin/polkadot-runtime-templates#352]
### templates

- [X] Generic Runtime Template
- [X] Evm Template

### What happened?

If people follow our guides, they will encounter the following error:
```
Error:           Error: Command failed with exit code 1: bash -c ./bin-stable2407-1/polkadot build-spec --chain paseo-local --disable-default-bootnode > /var/folders/gz/2t0xjdgd2738_r1lb311drmr0000gn/T/zombie-25472a6e5cb2d376cfb2189c4d4925a3_-81300-S69Q3Tes8WRi/cfg/paseo-local-plain.json
Error: 
   0: Invalid input: Error opening spec file `paseo-local`: No such file or directory (os error 2)
```

This may be due to the `polkadot` executable we are using in our zombienet config. Will investiage more

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines

**Comment by ozgunozerk** [comment]
Here is how it worked before with `rococo-local`: https://github.com/paritytech/polkadot-sdk/blob/polkadot-stable2407-1/polkadot/cli/src/command.rs#L99

Basically, the cli has `rococo-local` option hardcoded into it. But it doesn't have the same for `paseo-local`

**Comment by AlexD10S** [comment]
In the meantime, running `pop up parachain -f zombienet-config/devnet.toml`  installing pop from the branch: `cargo install --locked --git https://github.com/r0gue-io/pop-cli --branch oz-evm-template --force`
